// Checks that every Obsidian class the theme relies on still exists in the installed Obsidian.
// Usage: node tests/selectors.mjs [--asar <path>] [--write] [--strict]
//   --write   regenerate docs/internal-selectors.md
//   --strict  exit 1 when a core class is missing (plugin classes are only reported)
import { readFileSync, writeFileSync, existsSync, readdirSync } from "node:fs";
import { join } from "node:path";

const args = process.argv.slice(2);
const opt = (n, d) => { const i = args.indexOf(`--${n}`); return i >= 0 ? args[i + 1] : d; };
// Obsidian self-updates into %APPDATA%\obsidian\obsidian-<version>.asar; the installer copy can be older.
const latestAsar = () => {
  const dir = join(process.env.APPDATA ?? "", "obsidian");
  if (!existsSync(dir)) return null;
  const f = readdirSync(dir).filter(n => /^obsidian-[\d.]+\.asar$/.test(n))
    .sort((a, b) => a.localeCompare(b, undefined, { numeric: true })).pop();
  return f ? join(dir, f) : null;
};
const asar = opt("asar", latestAsar() ?? join(process.env.LOCALAPPDATA ?? "", "Programs", "Obsidian", "resources", "obsidian.asar"));
console.log(`bundle: ${asar}`);
if (!existsSync(asar)) { console.error(`Obsidian bundle not found: ${asar} (use --asar)`); process.exit(2); }

const css = readFileSync("theme.css", "utf8")
  .replace(/\/\*[\s\S]*?\*\//g, "")
  .replace(/"(?:[^"\\]|\\.)*"|'(?:[^'\\]|\\.)*'/g, '""')
  .replace(/url\([^)]*\)/g, "url()");

// Selector preludes only: text before "{" that is not an at-rule or a declaration.
const used = new Set();
for (const m of css.matchAll(/([^{};]+)\{/g)) {
  const sel = m[1].trim();
  if (sel.startsWith("@")) continue;
  for (const c of sel.matchAll(/\.(-?[_a-zA-Z][\w-]*)/g)) used.add(c[1]);
}

const bundle = readFileSync(asar, "latin1");
const known = new Set(bundle.match(/[A-Za-z_][\w-]*/g));

const OWN = /^bp-/;
const PLUGIN = /^(nn-|git-|commit-|has-feature-image|is-today|obsidian-git|calendar|cm-|HyperMD|cm6|style-settings|setting-item-|tippy)/;
const core = [...used].filter(c => !OWN.test(c)).sort();
const missing = core.filter(c => !known.has(c));
const missingCore = missing.filter(c => !PLUGIN.test(c));
const missingPlugin = missing.filter(c => PLUGIN.test(c));

console.log(`${core.length} non-Bliss classes used; ${core.length - missing.length} found in Obsidian`);
if (missingPlugin.length) console.log(`plugin/editor classes not in the bundle (informational): ${missingPlugin.join(" ")}`);
if (missingCore.length) console.log(`MISSING from Obsidian (renamed or removed?): ${missingCore.join(" ")}`);

if (args.includes("--write")) {
  const found = core.filter(c => known.has(c));
  writeFileSync("docs/internal-selectors.md",
    `# Internal selectors\n\nObsidian classes that \`theme.css\` depends on. Generated by \`node tests/selectors.mjs --write\`; after an Obsidian update, run \`npm run selectors\` and check for anything MISSING.\n\n## Core (${found.length})\n\n${found.map(c => `- \`.${c}\``).join("\n")}\n\n## Plugins and editor (${missingPlugin.length + core.filter(c => PLUGIN.test(c) && known.has(c)).length})\n\n${core.filter(c => PLUGIN.test(c)).map(c => `- \`.${c}\``).join("\n")}\n`);
  console.log("wrote docs/internal-selectors.md");
}
process.exit(args.includes("--strict") && missingCore.length ? 1 : 0);
