blank_issues_enabled: false
contact_links:
  - name: Bliss README
    url: https://github.com/itsjusthaif/obsidian-bliss#readme
    about: Installation, Style Settings options and plugin support.
